name: xlerate
description: One package that manages design, responsiveness and quicker development.
version: 2.5.2
homepage: https://github.com/dev-o-los/xlerate

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
