name: simple_sizer
description: One package that manages design, responsiveness and quicker development.
version: 0.9.1
homepage: https://github.com/dev-o-los/simple_sizer

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
